microsoft/windows-drivers-rs

README.md

docs: add crates.io release policy + minor fixes

---

.github/workflows/cargo-audit.yaml

Previously, cargo audit didn't run on PRs if the lockfiles or manifest did not change. Now, it will always run on PR builds, which allows us to block merges if it detects any unaddressed issues.

ci: run cargo audit for all pull requests

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

This reverts commit 16cc3a0230330e5bd7f3ae00e603f2bbd82aee12.
A new nightly was released with the fix minutes after I completed #63 which had a commit disabling nightly 🤦

ci: re-enable nightly in CI

---

.github/workflows/build.yaml
.github/workflows/cargo-audit.yaml
.github/workflows/code-formatting-check.yaml
.github/workflows/docs.yaml
.github/workflows/github-dependency-review.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

add `merge_group` ci trigger so that Github Merge queues can be used

ci: trigger github actions on merge_group

---

crates/wdk-build/src/bindgen.rs
crates/wdk-sys/generated_bindings/constants.rs

Per https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.generate_cstr, this will eventually be the default behaviour of bindgen in a future release. This option makes bindgen generate `&CStr` instead of ` &[u8]` for c string constants. This allows access to many convenience functions that make the c string constant safer and easier to work with. `CStr` also has no additional memory footprint compared to `[u8]`

feat: generate CStr for c string constants instead of &[u8]

---

.github/workflows/build.yaml
.github/workflows/code-formatting-check.yaml
.github/workflows/docs.yaml
.github/workflows/github-dependency-review.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
.gitignore
CONTRIBUTING.md
Cargo.lock
Makefile.toml
README.md
crates/sample-kmdf-driver/Cargo.toml
crates/sample-kmdf-driver/Makefile.toml
crates/sample-kmdf-driver/README.md
crates/wdk-build/Cargo.toml
crates/wdk-build/src/bindgen.rs
crates/wdk-build/src/cargo_make.rs
crates/wdk-build/src/lib.rs
crates/wdk-build/src/utils.rs
crates/wdk/src/lib.rs
rust-driver-makefile.toml

This PR consists of various fixes and features that resolve outstanding issues when compiling for arm64. Enhancements to the build and packaging, while made with the purpose of improving the arm64 experience, it does also add new features and improve the experience for non-arm64 builds (see README)
Outstanding Issues for this PR:
~- [ ] embed signature in sys file before signing cat, so that default flow works for boot-start drivers~ moved to separate PR #79 
fixes #14

Arm64 Build and Packaging Improvements

---

.github/workflows/build.yaml
Makefile.toml
crates/sample-kmdf-driver/src/lib.rs
crates/wdk-alloc/src/lib.rs
crates/wdk-build/src/lib.rs
crates/wdk-macros/src/lib.rs
crates/wdk-panic/src/lib.rs
crates/wdk-sys/src/lib.rs
crates/wdk/src/lib.rs
rust-driver-makefile.toml

Per https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html, deny(warnings) is an anti-pattern. Instead, warnings will now only fail in CI or when running cargo-make (in this repo). Warnings in rust-script blocks were also fixed.
pending merge of  #79 . review top 3 commits

fix: resolve warnings in rust-script blocks and only fail warnings in CI

---

Cargo.lock
Makefile.toml
README.md
crates/sample-kmdf-driver/Makefile.toml
crates/wdk-build/Cargo.toml
crates/wdk-build/rust-driver-makefile.toml
crates/wdk-build/src/cargo_make.rs
crates/wdk-build/src/lib.rs

Allows for downstream drivers to avoid needing to use pwsh to download the makefile, since its already included in the wdk-build source.
pending merge of #87. Review only the top commit
Also blocked on bug in https://github.com/sagiegurari/cargo-make/issues/1035

feat: package rust-driver-makefile.toml with wdk-build package

---

crates/wdk-build/src/cargo_make.rs
crates/wdk-sys/src/constants.rs
crates/wdk-sys/src/types.rs

These lint errors have been causing nightly clippy to fail since 2024-02-10

refactor: add lint exceptions for clippy::manual_c_str_literals and clippy::ref_as_ptr

---

.github/actions/winget-install/action.yml
.github/workflows/code-formatting-check.yaml
README.md
crates/wdk-build/rust-driver-makefile.toml
crates/wdk-build/src/bindgen.rs
crates/wdk-build/src/cargo_make.rs
crates/wdk-build/src/lib.rs
crates/wdk-build/src/utils.rs
crates/wdk-macros/tests/nightly/trybuild/wdf_driver_create_wrong_arg_order.rs
crates/wdk-macros/tests/nightly/trybuild/wdf_driver_create_wrong_arg_order.stderr
crates/wdk-macros/tests/non-nightly/trybuild/wdf_driver_create_wrong_arg_order.rs
crates/wdk-macros/tests/non-nightly/trybuild/wdf_driver_create_wrong_arg_order.stderr
crates/wdk-sys/src/test_stubs.rs

Various issues are causing pipelines to fail right now:
- latest winget requires new version of xaml to be installed: https://github.com/microsoft/winget-cli/issues/4208
- nightly rustfmt was broken upstream: https://github.com/rust-lang/rustfmt/issues/6082, https://github.com/rust-lang/rustfmt/issues/6099
- various new clippy lints began triggering

ci: fix various pipeline breakages (nightly rustfmt bug, new nightly clippy lints, upstream winget dependency issue)

---

.github/workflows/test.yaml
CONTRIBUTING.md
README.md
crates/sample-kmdf-driver/build.rs
crates/wdk-build/src/lib.rs
crates/wdk-sys/build.rs
crates/wdk-sys/src/test_stubs.rs

BREAKING CHANGES: wdk_build::Config::configure_binary_build now returns a wdk_build::ConfigError instead of ().
This fixes execution of wdk-sys test in certain environments(ie. github windows runners) and should also allow crates that depend on `wdk-sys` to compile and run unit tests without linking against kernel libraries.

fix!: prevent linking of wdk libraries in tests that depend on `wdk-sys`

---

.github/workflows/test.yaml
CONTRIBUTING.md
Makefile.toml
crates/wdk-sys/src/constants.rs
crates/wdk-sys/src/types.rs

fixes breakage in beta pipeline

refactor: change version bounds for `manual_c_str_literals` and `ref_as_ptr` clippy lints

---

.github/workflows/docs.yaml
.github/workflows/github-dependency-review.yaml
Cargo.lock
Cargo.toml
Makefile.toml
crates/sample-kmdf-driver/Cargo.toml
crates/sample-kmdf-driver/build.rs
crates/sample-kmdf-driver/src/lib.rs
crates/wdk-alloc/Cargo.toml
crates/wdk-alloc/src/lib.rs
crates/wdk-build/Cargo.toml
crates/wdk-build/build.rs
crates/wdk-build/src/lib.rs
crates/wdk-macros/Cargo.toml
crates/wdk-macros/src/lib.rs
crates/wdk-panic/Cargo.toml
crates/wdk-panic/src/lib.rs
crates/wdk-sys/Cargo.toml
crates/wdk-sys/build.rs
crates/wdk-sys/src/lib.rs
crates/wdk/Cargo.toml
crates/wdk/build.rs
crates/wdk/src/lib.rs
crates/wdk/src/wdf/spinlock.rs
crates/wdk/src/wdf/timer.rs

Since the lints table feature has been released for the last 2 stable rust versions, I've migrated all of our linting configurations to use it so we can keep the configuration mostly in one place. 
Unfortunately, due to https://github.com/rust-lang/cargo/issues/13157, we cannot override workspace level lints yet, so several of the packages have locally defined lints in their Cargo manifest. This is still an improvement over before as now it applies at a package level instead of at the module level (and has caught several small issues)

refactor: use a standardized workspace lint table

---

.github/workflows/lint.yaml
crates/wdk-build/build.rs
crates/wdk-build/src/lib.rs

This change updates the cargo output to the new format (it is backwards compatible) and also fixes a compile warning introduced by the addition of the `rustc-check-cfg` feature: https://blog.rust-lang.org/2024/05/06/check-cfg.html

refactor: add support for rustc-check-cfg

---

crates/wdk-build/src/bindgen.rs
crates/wdk-sys/build.rs

When compiling this repo (or projects that depend on it), a large portion of the build time is spent waiting for bindgen to finish constructing bindings to the WDK.  This can severely slow down iterative development and builds.
This PR makes a simple change to how we call bindgen by calling each function wrapping a call to it in parallel.  On my machine this provides a speedup of running "cargo make" in windows-drivers-rs of about 20% (~500 seconds run time to ~400 seconds).
I wouldn't be surprised if we can refactor the calls even more to see greater speedups, but this was just a quick late afternoon project to speed up work on other features.

Build perf: Make calls to bindgen run in parallel

---

.github/actions/winget-install/action.yml
.github/workflows/build.yaml
.github/workflows/docs.yaml
.github/workflows/lint.yaml
.github/workflows/local-development-makefile.yaml
.github/workflows/test.yaml

As documented in #115 , LLVM 18 is bugged for arm64 targets. 
This PR:
* adds an additional CI matrix entry to test on specific LLVM versions instead of using whatever version is in the [github windows runner image](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md)
* currently only testing on latest LLVM 17
* switches all winget commands to use the new winget powershell module so its easier to parse output

ci: pin LLVM version in pipelines

---

crates/wdk-build/src/cargo_make.rs
crates/wdk-build/src/metadata/mod.rs
crates/wdk-macros/src/lib.rs
crates/wdk-sys/src/test_stubs.rs

Starting in `nightly-2024-08-26`, `too_long_first_doc_paragraph` is triggering on some of the doc comments

refactor: Improve doc comments to comply with `too_long_first_doc_paragraph` clippy lint

---

crates/wdk-macros/README.md
crates/wdk-macros/src/lib.rs
tests/wdk-macros-tests/README.md
tests/wdk-macros-tests/src/lib.rs
tests/wdk-macros-tests/tests/inputs/macrotest/bug_tuple_struct_shadowing.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/bug_tuple_struct_shadowing.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_driver_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_spin_lock_acquire.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/bug_tuple_struct_shadowing.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_driver_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_spin_lock_acquire.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/bug_tuple_struct_shadowing.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_driver_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_spin_lock_acquire.expanded.rs

`E0530 function parameters cannot shadow tuple structs` can sometimes be triggered when a new tuple struct is declared with the same name as the parameter name of WDF C function. This C parameter name is used inside the `call_unsafe_wdf_function_binding` macro, causing the shadowing error.
To fix this, the naming of the function parameters in the macro has been adjusted slightly to use names that are non-standard rust names (snake case post-fixed with a double underscore) in order to lessen the likelihood of a name clash.
side effect: macro usage sites have better syntax highlighting in IDE since the arguments of `call_unsafe_wdf_function_binding` are now detected as function arguments)

fix: prevent `E0530 function parameters cannot shadow tuple structs` error when using `call_unsafe_wdf_function_binding` 

---

crates/wdk-build/rust-driver-makefile.toml
crates/wdk-build/rust-driver-sample-makefile.toml

Closes #171 
With the recent merge of [Expand condition_script_runner_args #1132](https://github.com/sagiegurari/cargo-make/pull/1132) the `rust-condition-script-cargo_make_current_task_initial_makefile_directory-substitution` plugin is no longer needed. The `condition_script_runner_args` allows directly passing base path to the condition script runner. This PR updates the implementation by replacing the plugin with the `condition_script_runner_args`.

refactor: replace directory substitution plugin with condition_script_runner_args

---

crates/wdk-macros/src/lib.rs
examples/sample-kmdf-driver/src/lib.rs
tests/wdk-macros-tests/src/lib.rs
tests/wdk-macros-tests/tests/inputs/macrotest/bug_unused_imports.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/bug_unused_imports.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/bug_unused_imports.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_spin_lock_acquire.expanded.rs
tests/wdk-macros-tests/tests/outputs/beta/macrotest/wdf_verifier_dbg_break_point.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/bug_unused_imports.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/bug_unused_imports.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_driver_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_spin_lock_acquire.expanded.rs
tests/wdk-macros-tests/tests/outputs/nightly/macrotest/wdf_verifier_dbg_break_point.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/bug_tuple_struct_shadowing.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/bug_unused_imports.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/bug_unused_imports.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_device_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_device_create_device_interface.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_driver_create.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_request_retrieve_output_buffer.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_spin_lock_acquire.expanded.rs
tests/wdk-macros-tests/tests/outputs/stable/macrotest/wdf_verifier_dbg_break_point.expanded.rs

Fix for a bug where the wdk-sys types used in casts in arguments to the `call_unsafe_wdf_function_binding` macro would detected as unused imports. This was due to a glob import within the macro leaking outside of the macro.

fix: prevent unused import warning in arguments to `call_unsafe_wdf_function_binding`

---

crates/wdk-build/src/cargo_make.rs
rustfmt.toml

This pull request includes a small change to the rustfmt.toml file. The change removes the unstable version = "Two" setting, which was removed and replaced with the stable edition feature. The edition setting is auto-detected from the package rust edition.
Configuration updates:
* [`rustfmt.toml`](diffhunk://#diff-a947c9d2523f34e53b9cdcd6411174a3148f23ea03ad8a61c1aee7b3ea005440L39-L41): Removed the `version` setting, which was marked as unstable, to align with the latest `rustfmt` recommendations.

style: remove unstable `rustfmt` `version` setting (replaced by auto-detected `edition`)

---

crates/wdk-build/rust-driver-sample-makefile.toml
crates/wdk-build/src/cargo_make.rs
crates/wdk-build/src/lib.rs
crates/wdk-build/src/utils.rs

Closes #172 
- Moved the InfVerif task's condition script logic from rust-driver-sample-makefile.toml to a function in cargo-make.rs.
- Ensured the utils module remains private.

refactor: move infverif task's condition script logic to cargo_make.rs

---

crates/wdk-build/src/utils.rs

This pull request includes a small change to the `crates/wdk-build/src/utils.rs` file. The change involves removing an unnecessary blank line in the `PathExt` trait, that caused `clippy::empty-line-after-doc-comments` to trigger in latest nightly
* [`crates/wdk-build/src/utils.rs`](diffhunk://#diff-d0dc5143131ae33b24f02dd164505ab806c7136bc7822e77ff7d74152f7082e3L52): Removed an unnecessary blank line in the `strip_extended_length_path_prefix` method definition of the `PathExt` trait.

refactor: fix `clippy::empty-line-after-doc-comments` lint issues

---

crates/wdk-build/src/cargo_make.rs

This pull request includes changes to use `next_back` instead of `last` on double-ended iterators. This resolves the new `clippy::double_ended_iterator_last` lint. See https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last for more info on why this change is beneficial.
* [`crates/wdk-build/src/cargo_make.rs`](diffhunk://#diff-da58729eb32b74ae10c700766228300e3637a2f1141f291b8cd128497071bde3L1124-R1132): Updated the test assertions to use `next_back()` instead of `last()` to retrieve the last element of the split string.

refactor: use `next_back` instead of `last` on double-ended iterators (`clippy::double_ended_iterator_last`)

---

RELEASE.md

It seems that `release-plz` will silently skip running `cargo-semver-checks` if its not installed. Instructions have been clarified to make sure both tools are installed and updated

docs: Update RELEASE.md to include explicit cargo-semver-checks install

---

crates/wdk-build/src/utils.rs

This pull request includes a single change to the `detect_wdk_content_root` function in the `crates/wdk-build/src/utils.rs` file. The function had two equivalent branches that checked for `WDKContentRoot` env var and did the same thing with it. The 2nd redudant (and never executed) branch was removed.
* [`crates/wdk-build/src/utils.rs`](diffhunk://#diff-d0dc5143131ae33b24f02dd164505ab806c7136bc7822e77ff7d74152f7082e3L131-L143): Removed the block of code that checks the `WDKContentRoot` environment variable and handles its validity.

refactor: remove redundant code-path in `detect_wdk_content_root`

---

crates/wdk-build/rust-driver-makefile.toml
crates/wdk-build/src/cargo_make.rs

Ported last Duckscript condition script to Rust
closes #93

refactor: port certificate-generation condition script to Rust

---

crates/wdk-build/src/lib.rs
tests/wdk-macros-tests/README.md

This pull request includes changes to the `crates/wdk-build/src/lib.rs` file to add support for ARM64-specific libraries in the build process. The changes ensure that when the CPU architecture is ARM64, the appropriate ARM64 libraries are linked.
ARM64 support:
* Added conditional statements to link the `arm64rt` library if the CPU architecture is ARM64. [[1]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26R701-R706) [[2]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26R726-R731)

fix: add missing arm64rt library to linker flags for arm64 kernel-mode builds

---

crates/wdk-build/src/lib.rs

This pull request involves a few minor changes to the `crates/wdk-build/src/lib.rs` file. The changes mainly focus on removing the `#[must_use]` attribute from the `default` implementations of several configuration structs. This attribute was a noop since rustc doesn't support `must_use` on trait impls
Changes include:
* [`crates/wdk-build/src/lib.rs`](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26L213): Removed the `#[must_use]` attribute from the `default` implementations of `Config`, `KmdfConfig`, and `UmdfConfig`. [[1]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26L213) [[2]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26L954) …

refactor: remove noop `must_use` on trait impl

---

crates/wdk-build/src/bindgen.rs
crates/wdk-build/src/lib.rs
crates/wdk-sys/Cargo.toml
crates/wdk-sys/build.rs
crates/wdk-sys/src/lib.rs
crates/wdk-sys/src/usb.rs
examples/sample-kmdf-driver/Cargo.toml
examples/sample-umdf-driver/Cargo.toml
examples/sample-wdm-driver/Cargo.toml

This pull request introduces several changes to add support for USB APIs from the Windows Driver Kit (WDK) build system. The most important changes include adding a new API subset for USB, updating configuration to handle USB headers, and updating various Cargo.toml files to include the new `usb` feature.
Enhancements for USB driver support:
* [`crates/wdk-build/src/lib.rs`](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26R210-R211): Added a new `ApiSubset::Usb` variant and updated the `headers` method to include USB headers. Also, added logic to include `ufxclient.h` based on the Clang version. [[1]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26R210-R211) [[2]](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb16 …

feat: extend coverage in `wdk-sys` to include usb-related headers

---

crates/wdk-sys/src/lib.rs

Drivers that use the `wdk_sys::PAGED_CODE` macro used to have to separately import `wdk_sys::ntddk::KeGetCurrentIrql` and `wdk_sys::APC_LEVEL` in order to get the expanded macro to compile.
This change introduces absolute paths in `wdk_sys::PAGED_CODE` so that developers do not have to introduce these `use` statements to their code.

fix: use absolute paths for items used in PAGED_CODE macro

---

Cargo.lock
Cargo.toml
crates/wdk-macros/Cargo.toml
crates/wdk-macros/src/lib.rs
crates/wdk-sys/build.rs
crates/wdk-sys/src/ntddk.rs
crates/wdk-sys/src/test_stubs.rs
crates/wdk-sys/src/types.rs
examples/sample-kmdf-driver/Cargo.lock
examples/sample-umdf-driver/Cargo.lock
examples/sample-wdm-driver/Cargo.lock
tests/config-kmdf/Cargo.lock
tests/config-umdf/Cargo.lock
tests/mixed-package-kmdf-workspace/Cargo.lock
tests/umdf-driver-workspace/Cargo.lock
tests/wdk-sys-tests/Cargo.lock

Currently, our automated test matrix is not testing bindings when the WDK configuration is enabled at the project level. Locally, @wmmc88 discovered that the following `wdk-macros` tests failed when enabling the KMDF configuration:
- `tests::get_wdf_function_info_map::valid_input_no_cache`
- `tests::get_wdf_function_info_map::valid_input_cache_exists`
- `tests::inputs::generate_derived_ast_fragments::valid_input`
- `tests::inputs::generate_derived_ast_fragments::valid_input_with_no_arguments`.
These all test the feature I developed in #295 .
These tests failed with configuration turned on because of the `wdk` crate. We [conditionally compile](https://github.com/microsoft/windows-drivers-rs/blob/0ae8259826784334cf197bc9355b2ef011b70ec1/crates/wdk/src/lib.rs#L37) the abstractions contained …

fix: passing cache tests when WDK config is enabled

---

crates/wdk-sys/src/types.rs

Rust 1.88 beta includes the `unnecessary_transmutes` lint. Bindgen generates code that triggers this lint in `types.rs`. We need to silence this lint for this version of Rust and onwards.
Link to failing pipeline: https://github.com/microsoft/windows-drivers-rs/actions/runs/14955151207/job/42009809414

fix: allow unnecessary_transmutes lint for bindgen-generated types.rs

---

crates/wdk-build/src/lib.rs

This pull request updates the `emit_check_cfg_settings` function in the `Config` implementation within `crates/wdk-build/src/lib.rs` to improve its usability and documentation.
Enhancements to function usability and documentation:
* [`crates/wdk-build/src/lib.rs`](diffhunk://#diff-43524f733cccc1a175c3bf83309866acb53b8cadb1628478ca1c87d31dda2b26L304-R310): Changed the visibility of the `emit_check_cfg_settings` function from private (`fn`) to public (`pub fn`) and added detailed documentation explaining its purpose and usage. This makes the function accessible outside the module and clarifies its role in emitting `cargo::rustc-check-cfg` directives for potential `rustc-cfg` settings.

feat: make `emit_check_cfg_settings` function public

---

.github/workflows/codeql.yml
Cargo.lock
crates/wdk-build/Cargo.toml
crates/wdk-build/rust-driver-makefile.toml
crates/wdk-build/src/lib.rs
crates/wdk-build/src/utils.rs
crates/wdk-sys/build.rs

When tested with WDK Version 22621, the following bug was found - 
`--- stderr
D:\a\windows-drivers-rs\windows-drivers-rs\crates\wdk-sys\types-input.h:53:10: fatal error: 'ucx/1.6/ucxclass.h' file not found`
https://github.com/microsoft/windows-drivers-rs/actions/runs/15851446771/job/44685702556#step:9:1631
Instead of using version `1.6`, the latest version of `ucx` available in the `$WDKContentRoot\Include\10.0.26100.0\km\ucx` directory is used.
Summary of changes,
1. `ucx_header_path` function in `impl Config` that determines the latest version of UCX header in the directory.
2. `utils::find_max_version_in_directory` function to find the max version in a directory that contains folders of the form `x.y` where x and y are valid `u32`s.
3. Extracted `windows_sdk_library_path` construction …

fix: use latest version of ucx in the WDKContent as default

---

crates/cargo-wdk/src/cli.rs
crates/cargo-wdk/tests/build_command_test.rs
crates/cargo-wdk/tests/new_command_test.rs
crates/wdk-build/src/utils.rs

This PR improves cargo-wdk tests by:
- Reducing code duplication
- Shortening tests names to make them easier to understand
I wanted to do this for [crates/cargo-wdk/src/actions/build/tests.rs](https://github.com/microsoft/windows-drivers-rs/blob/main/crates/cargo-wdk/src/actions/build/tests.rs) as well but those tests are more complex and therefore require more thinking. Will open a different PR for them.

refactor: improve cargo-wdk tests

---

crates/cargo-wdk/src/main.rs
crates/wdk-build/src/lib.rs
crates/wdk-macros/src/lib.rs
crates/wdk/src/lib.rs

This pull request focuses on improving documentation consistency and clarity across multiple crates in the project. The main updates involve standardizing crate references in documentation comments, correcting links to use the appropriate Rust or HTML formats, and clarifying crate names for better readability and navigation.
**Documentation consistency and crate references:**
* Standardized documentation comments in `crates/cargo-wdk/src/main.rs` and `crates/wdk-build/src/lib.rs` to refer to the crate using the `[crate]` link format, improving consistency and navigation for users. [[1]](diffhunk://#diff-57ca2925fe256e6a174eef8879c726310cc5c61df5c0808359176e085fbf52f8L3-R3) [[2]](diffhunk://#diff-57ca2925fe256e6a174eef8879c726310cc5c61df5c0808359176e085fbf52f8L19-R19) …

docs: update crate references for consistency in documentation

---

crates/cargo-wdk/Cargo.toml

Changes in this PR:
1. Changed the `categories` field from "build-tools" to some [valid category values](https://crates.io/category_slugs) because invalid values would prevent the crate from being published. 
2. Replaced "Cargo subcommand" with "Cargo extension" in the description since that's more accurate.

docs: change categories in cargo-wdk to known slugs

---

crates/wdk-sys/src/lib.rs

Certain build environments may use version 4 of EH frame handlers and hit the same issue that prompted adding the `__CxxFrameHandler3` stub. This change is adding two more stubs, `__CxxFrameHandler4` and `__GSHandlerCheck_EH4`, and makes sure they are not folded (have distinct addresses in the resulting binary) by returning distinct values.
None of these functions will ever execute. They are a workaround for a compiler design issue which will take some time to resolve.

Add stubs for __CxxFrameHandler4 and __GSHandlerCheck_EH4

---

.github/workflows/build.yaml
.github/workflows/cargo-audit.yaml
.github/workflows/code-formatting-check.yaml
.github/workflows/codeql.yaml
.github/workflows/docs.yaml
.github/workflows/github-dependency-review.yaml
.github/workflows/lint.yaml
.github/workflows/local-development-makefile.yaml
.github/workflows/test.yaml
.github/workflows/typos.yaml

This pull request updates all GitHub Actions workflow files to improve CI reliability and efficiency. The main changes are the exclusion of the `gh-readonly-queue/**` branch from triggering workflows and an enhancement to how workflow concurrency groups are determined, which helps prevent duplicate runs and manages job cancellations more effectively. The new concurrency group is based off of investigations documented in https://github.com/scratchfoundation/understand-gha-triggers/blob/08a636e24d25f19c6f3691c06dd8fe86e184104d/README.md#understanding-github-actions-triggers
**Workflow trigger improvements:**
* Added `branches-ignore: ['gh-readonly-queue/**']` to the `push` event for all workflows, so jobs won't run for pushes to the `gh-readonly-queue/**` branch. …

ci: update workflows to ignore merge queue branches

---

crates/wdk-build/src/bindgen.rs
crates/wdk-build/src/lib.rs

feat: enhance debug tracing in bindgen and config modules
